name: cubezapp
description: A nice cube timer
dependencies:
  browser: any
  crystal:
    git: https://github.com/unixpickle/crystal.git
    version: 0.0.7
  pentagons: 1.0.0
  presenter: 0.0.13
  static: any
